version: '3'

services:

  app:
    build: .
    container_name: gobarber_backend
    ports:
      - 3333:3333
    networks:
      - postgres-compose-network
    depends_on:
      - "postgresDB"
    restart: always

  postgresDB:
    image: postgres:alpine
    container_name: banco-postgres
    environment:
      - POSTGRES_PASSWORD=123456
      - POSTGRES_DB=postgres
    ports:
      - "15432:5432"
    volumes:
      - db_data:/var/lib/postgresql/data
    networks:
      - postgres-compose-network

#   pgAdmin:
#     image: dpage/pgadmin4
#     environment:
#       PGADMIN_DEFAULT_EMAIL: "delfio_eu@hotmail.com"
#       PGADMIN_DEFAULT_PASSWORD: "123456"
#     ports:
#       - "16543:80"
#     depends_on:
#       - postgresDB
#     networks:
#       - postgres-compose-network

volumes:
  db_data:

networks:
  postgres-compose-network:
    driver: bridge
