
version: '3'

services:
  app:
    build: ../
    container_name: gobarber_backend
    ports:
      - 3333:3333
    networks:
      - gobarber-network
    restart: always

networks:
  gobarber-network:
    driver: bridge
